# syntax=docker/dockerfile:1
ARG VOLTO_VERSION
FROM plone/frontend-dev:${VOLTO_VERSION} as builder

ARG ADDON_NAME
ARG ADDON_PATH

COPY --chown=node:node . /app/src/addons/${ADDON_PATH}/

RUN <<EOT
    set -e
    /setupAddon
    yarn install --network-timeout 1000000
    yarn build
    rm -rf cache omelette .yarn/cache
EOT

FROM plone/frontend-prod-config:${VOLTO_VERSION}

# Copy Volto project
COPY --from=builder /app/ /app/
